# Generated by Django 2.2.6 on 2020-03-01 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_notes', '0002_auto_20200214_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AccountInfo',
        ),
    ]
