# Generated by Django 3.0.4 on 2020-06-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_notes', '0008_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetinfo',
            old_name='items',
            new_name='item',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
