# Generated by Django 3.0.4 on 2020-06-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_notes', '0009_auto_20200603_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='income',
            field=models.FloatField(default=0),
        ),
    ]
